
# 

LETTER = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
DIGIT = "0123456789"

UNDERSCORE = "_"
L_PARENTHESIS = "("
R_PARENTHESIS = ")"
L_BRACKET = "["
R_BRACKET = "]"
COMA = ","
DOT = "."
SEMICOLON = ";"

# Symbols
QUESTION_MARK = "?"
EQUAL = "="
MULTIPLICATION = "*"
DIVISION = "/"
ADDITION = "+"
SUBTRACTION = "-"
NEGATE = "-"
MODULO = "%"
POWER = "^"
IMAGINARY_I = "i"

# Tokenizer elements
WHITESPACES = "\t "
RATIONAL = DIGIT + DOT
IMAGINARY = RATIONAL + IMAGINARY_I
NAME = LETTER + UNDERSCORE
DELIMITER = L_PARENTHESIS + R_PARENTHESIS + L_BRACKET + R_BRACKET + COMA + SEMICOLON
SYMBOL = EQUAL + MULTIPLICATION + DIVISION + ADDITION + SUBTRACTION + MODULO + POWER + QUESTION_MARK
 